"""
Email notification channel using SMTP.
"""

import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, List

from src.alerts.channels.base_channel import BaseChannel

logger = logging.getLogger(__name__)


class EmailChannel(BaseChannel):
    """Email notification channel via SMTP"""

    def __init__(self, config: Dict):
        """
        Initialize email channel.

        Args:
            config: Email configuration dict with SMTP settings
        """
        self.smtp_host = config['smtp_host']
        self.smtp_port = config.get('smtp_port', 587)
        self.smtp_user = config['smtp_user']
        self.smtp_password = config['smtp_password']
        self.use_tls = config.get('use_tls', True)
        self.from_address = config['from_address']
        self.to_addresses = config['to_addresses']

        if not isinstance(self.to_addresses, list):
            self.to_addresses = [self.to_addresses]

        logger.info(f"Email channel initialized (host: {self.smtp_host}, port: {self.smtp_port})")

    def send(self, rule, value: float, labels: Dict[str, str]) -> bool:
        """
        Send email notification.

        Args:
            rule: AlertRule instance
            value: Current metric value
            labels: Metric labels

        Returns:
            True if sent successfully
        """
        try:
            # Format message
            message_content = self.format_message(rule, value, labels)

            # Create email
            subject = f"[{rule.severity.upper()}] {message_content['summary']}"
            body = self._create_email_body(rule, value, labels, message_content)

            # Send email
            self._send_smtp(subject, body)

            logger.info(f"Email sent for alert: {rule.name}")
            return True

        except Exception as e:
            logger.error(f"Failed to send email for alert {rule.name}: {e}")
            return False

    def _create_email_body(self, rule, value: float, labels: Dict[str, str],
                          message_content: Dict[str, str]) -> str:
        """Create HTML email body"""
        severity_colors = {
            'info': '#0066cc',
            'warning': '#ff9900',
            'critical': '#cc0000',
        }
        color = severity_colors.get(rule.severity, '#666666')

        # Format labels
        labels_html = ""
        if labels:
            labels_html = "<h3>Labels:</h3><ul>"
            for key, val in labels.items():
                labels_html += f"<li><strong>{key}:</strong> {val}</li>"
            labels_html += "</ul>"

        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <div style="border-left: 4px solid {color}; padding-left: 15px; margin-bottom: 20px;">
                <h2 style="color: {color}; margin: 0;">{message_content['summary']}</h2>
                <p style="color: #666; margin: 5px 0 0 0;">Severity: {rule.severity.upper()}</p>
            </div>

            <p style="font-size: 16px; line-height: 1.5;">
                {message_content['description']}
            </p>

            <hr style="border: 0; border-top: 1px solid #ddd; margin: 20px 0;">

            <h3>Alert Details:</h3>
            <ul>
                <li><strong>Rule:</strong> {rule.name}</li>
                <li><strong>Metric:</strong> {rule.metric_name}</li>
                <li><strong>Condition:</strong> {rule.operator} {rule.threshold}</li>
                <li><strong>Current Value:</strong> {value:.2f}</li>
            </ul>

            {labels_html}

            <hr style="border: 0; border-top: 1px solid #ddd; margin: 20px 0;">

            <p style="color: #999; font-size: 12px;">
                This alert was generated by the Metrics Monitoring Agent.
            </p>
        </body>
        </html>
        """

        return html

    def _send_smtp(self, subject: str, body: str) -> None:
        """
        Send email via SMTP.

        Args:
            subject: Email subject
            body: Email body (HTML)

        Raises:
            Exception on SMTP errors
        """
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = self.from_address
        msg['To'] = ', '.join(self.to_addresses)

        # Attach HTML body
        html_part = MIMEText(body, 'html')
        msg.attach(html_part)

        # Send via SMTP
        with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=10) as server:
            if self.use_tls:
                server.starttls()

            server.login(self.smtp_user, self.smtp_password)
            server.send_message(msg)

        logger.debug(f"SMTP email sent to {self.to_addresses}")
